version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-arboles
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: arboles_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: flask-arboles
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: usuario
      DB_PASSWORD: userpassword
      DB_NAME: arboles_db
    depends_on:
      - mysql

volumes:
  mysql_data:
